
apiVersion: v1
kind: Route
metadata:
  name: mosquitto-tls
  labels:
    app: mosquitto-app
spec:
  to:
    kind: Service
    name: mosquitto-tls
  port:
    targetPort: 8883
  tls:
    termination: passthrough 